// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://takhin.io/terms",
        "contact": {
            "name": "Takhin Support",
            "url": "https://takhin.io/support",
            "email": "support@takhin.io"
        },
        "license": {
            "name": "Business Source License 1.1",
            "url": "https://github.com/redpanda-data/redpanda/blob/dev/licenses/bsl.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/consumer-groups": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all consumer groups with their status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consumer Groups"
                ],
                "summary": "List all consumer groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pkg_console.ConsumerGroupSummary"
                            }
                        }
                    }
                }
            }
        },
        "/consumer-groups/{group}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get detailed information about a specific consumer group",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Consumer Groups"
                ],
                "summary": "Get consumer group details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consumer group ID",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_console.ConsumerGroupDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check comprehensive health status of all components",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_console.HealthCheck"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Check if the service is alive (Kubernetes liveness probe)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Check if the service is ready to accept traffic (Kubernetes readiness probe)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/topics": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all topics with their partition information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Topics"
                ],
                "summary": "List all topics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pkg_console.TopicSummary"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new topic with the specified number of partitions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Topics"
                ],
                "summary": "Create a new topic",
                "parameters": [
                    {
                        "description": "Topic creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_console.CreateTopicRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/topics/{topic}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get detailed information about a specific topic",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Topics"
                ],
                "summary": "Get topic details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic name",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg_console.TopicDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a topic and all its data",
                "tags": [
                    "Topics"
                ],
                "summary": "Delete a topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic name",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/topics/{topic}/messages": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Fetch messages from a specific topic partition",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Get messages from a topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic name",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Partition ID",
                        "name": "partition",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Starting offset",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum number of messages to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/pkg_console.Message"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send a message to a specific topic partition",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Produce a message to a topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Topic name",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message to produce",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_console.ProduceMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pkg_console.ComponentHealth": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/pkg_console.HealthStatus"
                }
            }
        },
        "pkg_console.ConsumerGroupDetail": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkg_console.ConsumerGroupMember"
                    }
                },
                "offsetCommits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkg_console.ConsumerGroupOffsetCommit"
                    }
                },
                "protocol": {
                    "type": "string"
                },
                "protocolType": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "pkg_console.ConsumerGroupMember": {
            "type": "object",
            "properties": {
                "clientHost": {
                    "type": "string"
                },
                "clientId": {
                    "type": "string"
                },
                "memberId": {
                    "type": "string"
                },
                "partitions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "pkg_console.ConsumerGroupOffsetCommit": {
            "type": "object",
            "properties": {
                "metadata": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "partition": {
                    "type": "integer"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "pkg_console.ConsumerGroupSummary": {
            "type": "object",
            "properties": {
                "groupId": {
                    "type": "string"
                },
                "members": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "pkg_console.CreateTopicRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "partitions": {
                    "type": "integer"
                }
            }
        },
        "pkg_console.HealthCheck": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/pkg_console.ComponentHealth"
                    }
                },
                "status": {
                    "$ref": "#/definitions/pkg_console.HealthStatus"
                },
                "system_info": {
                    "$ref": "#/definitions/pkg_console.SystemInfo"
                },
                "timestamp": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "pkg_console.HealthStatus": {
            "type": "string",
            "enum": [
                "healthy",
                "degraded",
                "unhealthy"
            ],
            "x-enum-varnames": [
                "HealthStatusHealthy",
                "HealthStatusDegraded",
                "HealthStatusUnhealthy"
            ]
        },
        "pkg_console.Message": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "partition": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "pkg_console.PartitionInfo": {
            "type": "object",
            "properties": {
                "highWaterMark": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "pkg_console.ProduceMessageRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "partition": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "pkg_console.SystemInfo": {
            "type": "object",
            "properties": {
                "go_version": {
                    "type": "string"
                },
                "memory_mb": {
                    "type": "number"
                },
                "num_cpu": {
                    "type": "integer"
                },
                "num_goroutines": {
                    "type": "integer"
                }
            }
        },
        "pkg_console.TopicDetail": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "partitionCount": {
                    "type": "integer"
                },
                "partitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkg_console.PartitionInfo"
                    }
                }
            }
        },
        "pkg_console.TopicSummary": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "partitionCount": {
                    "type": "integer"
                },
                "partitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkg_console.PartitionInfo"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API Key authentication. Use 'your-api-key' or 'Bearer your-api-key' format.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Topic management operations",
            "name": "Topics"
        },
        {
            "description": "Message produce and consume operations",
            "name": "Messages"
        },
        {
            "description": "Consumer group monitoring operations",
            "name": "Consumer Groups"
        },
        {
            "description": "Health check endpoints",
            "name": "Health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Takhin Console API",
	Description:      "HTTP REST API for Takhin Console - manage topics, messages, and consumer groups",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
