version: '3'

# Global variables
vars:
  BACKEND_DIR: backend
  FRONTEND_DIR: frontend
  BINARY_NAME: takhin
  BUILD_DIR: build

# Tasks
tasks:
  # Backend tasks
  backend:deps:
    desc: Install backend dependencies
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go mod download
      - go mod tidy

  backend:build:
    desc: Build backend binary
    dir: '{{.BACKEND_DIR}}'
    deps: [backend:deps]
    cmds:
      - go build -o ../{{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/takhin
      - go build -o ../{{.BUILD_DIR}}/takhin-console ./cmd/console
      - go build -o ../{{.BUILD_DIR}}/takhin-debug ./cmd/takhin-debug
      - go build -o ../{{.BUILD_DIR}}/takhin-cli ./cmd/takhin-cli
      - go build -o ../{{.BUILD_DIR}}/takhin-schema-registry ./cmd/schema-registry
      - go build -o ../{{.BUILD_DIR}}/takhin-profiler ./cmd/takhin-profiler
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
    generates:
      - ../{{.BUILD_DIR}}/{{.BINARY_NAME}}
      - ../{{.BUILD_DIR}}/takhin-console
      - ../{{.BUILD_DIR}}/takhin-debug
      - ../{{.BUILD_DIR}}/takhin-cli
      - ../{{.BUILD_DIR}}/takhin-schema-registry

  backend:run:
    desc: Run backend server
    dir: '{{.BACKEND_DIR}}'
    deps: [backend:build]
    cmds:
      - ../{{.BUILD_DIR}}/{{.BINARY_NAME}} -config configs/takhin.yaml

  backend:test:
    desc: Run backend tests
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...

  backend:test:unit:
    desc: Run backend unit tests only
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go test -v -race -short ./...

  backend:test:e2e:
    desc: Run E2E tests
    cmds:
      - ./scripts/run_e2e_tests.sh all

  backend:test:e2e:quick:
    desc: Run quick E2E smoke tests
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go test -v -tags=e2e -timeout=10m ./tests/e2e/producer_consumer -run TestBasicProduceConsume
      - go test -v -tags=e2e -timeout=10m ./tests/e2e/admin_api -run TestCreateTopicAPI

  backend:bench:
    desc: Run backend storage benchmarks
    cmds:
      - ./scripts/run_benchmarks.sh

  backend:bench:quick:
    desc: Run quick storage benchmarks
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go test -bench=. -benchtime=1s -benchmem ./pkg/storage/log ./pkg/storage/topic

  backend:coverage:
    desc: Show backend test coverage
    dir: '{{.BACKEND_DIR}}'
    deps: [backend:test]
    cmds:
      - go tool cover -html=coverage.out

  backend:lint:
    desc: Run backend linter
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - golangci-lint run --timeout=5m

  cli:build:
    desc: Build CLI tool
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go build -o ../{{.BUILD_DIR}}/takhin-cli ./cmd/takhin-cli
    sources:
      - 'cmd/takhin-cli/**/*.go'
      - go.mod
      - go.sum
    generates:
      - ../{{.BUILD_DIR}}/takhin-cli

  backend:fmt:
    desc: Format backend code
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go fmt ./...
      - goimports -w .

  backend:grpc:proto:
    desc: Generate gRPC code from proto files
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - make -f Makefile.proto proto

  backend:grpc:test:
    desc: Run gRPC API tests
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go test -v -race ./pkg/grpcapi/...

  backend:grpc:bench:
    desc: Run gRPC API benchmarks
    dir: '{{.BACKEND_DIR}}'
    cmds:
      - go test -bench=. -benchmem -benchtime=5s ./pkg/grpcapi/

  backend:debug:
    desc: Generate debug bundle
    dir: '{{.BACKEND_DIR}}'
    deps: [backend:build]
    cmds:
      - ../{{.BUILD_DIR}}/takhin-debug -config configs/takhin.yaml

  backend:build:all:
    desc: Build for all platforms (Linux, macOS, Windows)
    cmds:
      - ./scripts/build-all.sh {{.VERSION | default "dev"}}

  backend:release:snapshot:
    desc: Create snapshot release with GoReleaser
    cmds:
      - goreleaser release --snapshot --clean --skip=sign

  backend:release:check:
    desc: Check GoReleaser configuration
    cmds:
      - goreleaser check

  backend:clean:
    desc: Clean backend build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}/{{.BINARY_NAME}}
      - rm -rf {{.BUILD_DIR}}/takhin-*
      - rm -rf {{.BACKEND_DIR}}/coverage.out
      - rm -rf dist/

  # Frontend tasks
  frontend:deps:
    desc: Install frontend dependencies
    dir: '{{.FRONTEND_DIR}}'
    cmds:
      - npm install

  frontend:dev:
    desc: Run frontend development server
    dir: '{{.FRONTEND_DIR}}'
    deps: [frontend:deps]
    cmds:
      - npm run dev

  frontend:build:
    desc: Build frontend for production
    dir: '{{.FRONTEND_DIR}}'
    deps: [frontend:deps]
    cmds:
      - npm run build

  frontend:preview:
    desc: Preview frontend production build
    dir: '{{.FRONTEND_DIR}}'
    deps: [frontend:build]
    cmds:
      - npm run preview

  frontend:lint:
    desc: Run frontend linter
    dir: '{{.FRONTEND_DIR}}'
    cmds:
      - npm run lint

  frontend:lint:fix:
    desc: Fix frontend linting issues
    dir: '{{.FRONTEND_DIR}}'
    cmds:
      - npm run lint:fix

  frontend:format:
    desc: Format frontend code
    dir: '{{.FRONTEND_DIR}}'
    cmds:
      - npm run format

  frontend:format:check:
    desc: Check frontend code formatting
    dir: '{{.FRONTEND_DIR}}'
    cmds:
      - npm run format:check

  frontend:type-check:
    desc: Run TypeScript type checking
    dir: '{{.FRONTEND_DIR}}'
    cmds:
      - npm run type-check

  frontend:clean:
    desc: Clean frontend build artifacts
    cmds:
      - rm -rf {{.FRONTEND_DIR}}/dist
      - rm -rf {{.FRONTEND_DIR}}/node_modules

  # Docker tasks
  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t takhin:latest -f deployments/Dockerfile .

  docker:run:
    desc: Run Docker container
    deps: [docker:build]
    cmds:
      - docker run -p 9092:9092 -p 9090:9090 takhin:latest

  # Development tasks
  dev:setup:
    desc: Setup development environment
    cmds:
      - task: backend:deps
      - task: frontend:deps
      - echo "Development environment setup complete"

  dev:check:
    desc: Run all checks before commit
    cmds:
      - task: backend:fmt
      - task: backend:lint
      - task: backend:test
      - task: frontend:lint:fix
      - task: frontend:format
      - task: frontend:type-check

  dev:all:
    desc: Run backend and frontend together
    cmds:
      - task: backend:run &
      - task: frontend:dev

  # Clean all
  clean:
    desc: Clean all build artifacts
    cmds:
      - task: backend:clean
      - task: frontend:clean
      - rm -rf {{.BUILD_DIR}}

  # Help
  default:
    desc: Show available tasks
    cmds:
      - task --list
