# Makefile for generating gRPC code from proto files

.PHONY: proto clean

proto:
	protoc --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative \
		api/proto/takhin.proto

clean:
	rm -f api/proto/*.pb.go
