// Copyright 2025 Takhin Data, Inc.
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Run `make proto` to regenerate this file from takhin.proto

package takhinpb

// Placeholder file - run `protoc` with protoc-gen-go-grpc plugin to generate
