// Copyright 2025 Takhin Data, Inc.
// Code generated by protoc-gen-go. DO NOT EDIT.
// Run `make proto` to regenerate this file from takhin.proto

package takhinpb

// Placeholder file - run `protoc` with protoc-gen-go plugin to generate
// This allows the project to compile without requiring protoc installation
// 
// To generate:
// 1. Install protoc: https://grpc.io/docs/protoc-installation/
// 2. Install Go plugins: 
//    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
// 3. Run: make -f Makefile.proto proto
